extracted_schema = [
	{'name': 'codigoOrgao',             	'dtype': 'int64', 		   'isActive': True},
	{'name': 'nomeOrgao',             		'dtype': 'object',		   'isActive': True},
	{'name': 'codigoUnidadeGestora',      	'dtype': 'int64', 		   'isActive':True},
	{'name': 'nomeUnidadeGestora',        	'dtype': 'object',		   'isActive': True},
	{'name': 'numeroContrato',            	'dtype': 'object',		   'isActive': True},
	{'name': 'niFornecedor',             	'dtype': 'int64', 		   'isActive': True},
	{'name': 'nomeRazaoSocialFornecedor', 	'dtype': 'object',		   'isActive':True},
	{'name': 'processo',             		'dtype': 'object',		   'isActive':True},
	{'name': 'objeto',             			'dtype': 'object',		   'isActive':True},
	{'name': 'dataVigenciaInicial',       	'dtype': 'datetime64[ns]', 'isActive': True},
	{'name': 'dataVigenciaFinal',         	'dtype': 'datetime64[ns]', 'isActive': True},
	{'name': 'valorGlobal',               	'dtype': 'float64', 			'isActive': True},
	{'name': 'numeroParcelas',            	'dtype': 'int64',   			'isActive': True},
	{'name': 'valorParcela',              	'dtype': 'float64', 			'isActive': True},
	{'name': 'valorAcumulado',            	'dtype': 'float64', 			'isActive': True},
	{'name': 'totalDespesasAcessorias',   	'dtype': 'float64', 			'isActive': True},
	{'name': 'numeroControlePncpContrato',	'dtype': 'float64', 			'isActive': True},
]